// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqoP-Jzdj9d_bG6m4NlI-8158x-SWx2uA',
    appId: '1:867917384783:web:f761de1a561c0ad3ceee3a',
    messagingSenderId: '867917384783',
    projectId: 'gardens-united',
    authDomain: 'gardens-united.firebaseapp.com',
    storageBucket: 'gardens-united.firebasestorage.app',
    measurementId: 'G-LWE5WQ2RHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqHsPy-nYYp-EfCVlPcjnmoIOaSMRGEgY',
    appId: '1:867917384783:android:971f2758c0ab08e3ceee3a',
    messagingSenderId: '867917384783',
    projectId: 'gardens-united',
    storageBucket: 'gardens-united.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgIyGoq46hhAs7bkxVjfFNJmyp5DUcgbg',
    appId: '1:867917384783:ios:00fcef55412427feceee3a',
    messagingSenderId: '867917384783',
    projectId: 'gardens-united',
    storageBucket: 'gardens-united.firebasestorage.app',
    iosClientId: '867917384783-42kkkvnrppb1ufj74cnr00m5ml8936ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.garden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgIyGoq46hhAs7bkxVjfFNJmyp5DUcgbg',
    appId: '1:867917384783:ios:00fcef55412427feceee3a',
    messagingSenderId: '867917384783',
    projectId: 'gardens-united',
    storageBucket: 'gardens-united.firebasestorage.app',
    iosClientId: '867917384783-42kkkvnrppb1ufj74cnr00m5ml8936ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.garden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqoP-Jzdj9d_bG6m4NlI-8158x-SWx2uA',
    appId: '1:867917384783:web:6397a08aa9a88f2dceee3a',
    messagingSenderId: '867917384783',
    projectId: 'gardens-united',
    authDomain: 'gardens-united.firebaseapp.com',
    storageBucket: 'gardens-united.firebasestorage.app',
    measurementId: 'G-8NFVXQN5QD',
  );

}